version: '2'

services:
  transmission:
    image: yuri1987/transmission
    container_name: transmission
    volumes:
    - /path/to/complete:/downloads
    - /path/to/incomplete:/incomplete
    environment:
    - WEBUSER=x
    - WEBPASS=x
    ports:
    - "10000:9091"
    - "51413:51413"
    - "51413:51413/udp"
